name: go_router_aggregator
description: >
  Aggregates GoRouter's generated type-safe routes into one importable file,
  separating your route declarations from the router setup.
version: 1.0.1
repository: https://github.com/mitryp/go_router_aggregator

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  # a workaround for a braking change in `build`
  # https://github.com/flutter/flutter/issues/170832
  build: ">=2.0.0 <2.5.0"
  glob: ^2.1.3
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.13
  build_test: ^2.2.2
  test: ^1.26.2

topics:
  - codegen
  - go-router
  - navigation
  - build-runner
