name: go_router_aggregator
description: A build_runner plugin that scans all *.g.dart files for $appRoutes and emits a merged aggregated_app_routes.g.dart.
version: 0.1.0
repository: https://github.com/mitryp/go_router_aggregator

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  build: ^2.4.1
  glob: ^2.1.3
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.13
  build_test: ^2.2.2
  test: ^1.26.2

topics:
  - codegen
  - go-router
  - navigation
  - build-runner
