// GENERATED by go_router_aggregator - do NOT edit by hand - contents will be overridden
// ignore_for_file: type=lint
import 'package:go_router/go_router.dart';

import 'package:go_router_aggregator_example/pages/home_page/home_page.dart' as _home_page0;
import 'package:go_router_aggregator_example/pages/shell/shell_page.dart' as _shell_page0;

List<RouteBase> get $aggregatedRoutes => [
  ..._home_page0.$appRoutes,
  ..._shell_page0.$appRoutes,
];
